# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.7
  hooks:
  - id: ruff
  - id: ruff-format

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-case-conflict
  - id: debug-statements
  - id: check-toml
  - id: detect-private-key
    language_version: python3

- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
  - id: isort
    name: isort (python)

- repo: local
  hooks:
  - id: gen-env-sample
    name: gen-env-sample
    entry: ./scripts/gen-env-sample.sh
    language: system
    types: [python]
    pass_filenames: false
